# docker-compose.yml
version: "3.9"

services:
  db:
    image: postgres:15
    container_name: task_list_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: task_list_web
    command: ["./entrypoint.sh"]
    volumes:
      - .:/rails
      - ./config/ssl:/rails/config/ssl
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SECRET_KEY_BASE: devplaceholderkey
    depends_on:
      - db

volumes:
  pg_data:
